languageCode = "en-ie"
languageName = "English (Ireland)"
displayName = ":flag-ie:"
isoCode = "en-IE"
weight = 1
rtl = false

title = "StrangeCharacters"
# logo = "img/logo.jpg"
description = "Doing things and writing about them."
copyright = "&copy;StrangeCharacters 2022 Congo contributors"

dateFormat = "2 January 2006"

[author]
  name = "Declan"
  image = "img/author.jpg"
  headline = "Making and breaking"
  bio = "Learning and documenting."
  links = [
    { twitter = "https://twitter.com/" },
    { facebook = "https://facebook.com/" },
    { linkedin = "https://linkedin.com/" },
    { youtube = "https://youtube.com/" },
  ]
