languageCode = "en-ie"
weight = 1
title = "StrangeCharacters"

params.languageName = "English (Ireland)"
params.displayName = ":flag-ie:"
params.isoCode = "en-IE"
params.rtl = false
params.description = "Doing things and writing about them."
params.dateFormat = "2 January 2006"

# logo = "img/logo.jpg"
copyright = "&copy;StrangeCharacters"




