# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "ocean"
defaultAppearance = "light" # valid options: light or dark
footer.autoSwitchAppearance = true
footer.showAppearanceSwitcher = true

enableSearch = true
enableCodeCopy = true

mainSections = ["articles"]
# robots = ""
footer.showScrollToTop = true
header.showTitle = true # name of the site shown in header

[homepage]
  layout = "basic" # valid options: page, profile, custom
  showRecent = true

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/jpanther/congo/tree/dev/exampleSite/content/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = false
  showTableOfContents = true
  showTaxonomies = false
  showWordCount = false
  # sharingLinks = ["facebook", "twitter", "pinterest", "reddit", "linkedin", "email"]

[list]
  showBreadcrumbs = true
  showSummary = false
  showTableOfContents = true
  groupByYear = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

[author]
  name = "Declan"
  #image = "img/author.jpg"
  headline = "Making and breaking"
  bio = "Learning and documenting."
  links = [
    { twitter = "https://twitter.com/strangechars" },
   # { facebook = "https://facebook.com/" },
   # { linkedin = "https://linkedin.com/" },
    { youtube = "https://youtube.com/" },
  ]

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
